export default {
  'ace-editor': '//cdnjs.cloudflare.com/ajax/libs/ace/1.9.5/ace.js',
  'babel-polyfill': './libraries/babel-polyfill.min.js',
  'backbone-forms-lists': './libraries/backbone-forms-lists.js',
  'backbone-forms': './libraries/backbone-forms.js',
  'backbone': './libraries/backbone.js',
  'ckeditor': '//cdn.ckeditor.com/4.5.7/full-all/ckeditor.js',
  'font-awesome': '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',
  'handlebars': './libraries/handlebars.js',
  'imageReady': './libraries/imageReady.js',
  'inview': './libraries/inview.js',
  'jquery-ui': './libraries/jquery-ui.min.js',
  'jquery.form': './libraries/jquery.form.js',
  'jquery': './libraries/jquery.js',
  'jquery.tagsinput': './libraries/jquery.tagsinput.min.js',
  'moment': './libraries/moment.min.js',
  'polyglot': './libraries/polyglot.min.js',
  'require': './libraries/require.js',
  'scrollTo': './libraries/scrollTo.js',
  'selectize': './libraries/selectize.js',
  'spectrum': './libraries/spectrum.js',
  'underscore': './libraries/underscore.js',
  'velocity': './libraries/velocity.js',
}